services:
  postgres-server:
    image: postgres:18
    container_name: go-postgres-server
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_DOCKER_PORT}"
    volumes:
      - ${POSTGRES_HOST_PATH}:${POSTGRES_DOCKER_PATH}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 5s

  postgres-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ${MIGRATE_HOST_PATH}:${MIGRATE_DOCKER_PATH}
    command:
      - "-path"
      - "${MIGRATE_DOCKER_PATH}"
      - "-database"
      - "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVICE}:${POSTGRES_DOCKER_PORT}/${POSTGRES_DB}?sslmode=disable"
      - "up"
    depends_on:
      postgres-server:
        condition: service_healthy

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: pgweb
    ports:
      - ${PGWEB_PORT}:8081
    environment:
      - PGWEB_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVICE}:${POSTGRES_DOCKER_PORT}/${POSTGRES_DB}?sslmode=disable
    depends_on:
      postgres-migrate:
        condition: service_completed_successfully

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - BACKEND_SERVER_HOST=0.0.0.0
      - BACKEND_SERVER_PORT=8080
      - WEBHOUND_ENV_FILE=
      - POSTGRES_HOST=${POSTGRES_SERVICE}
      - POSTGRES_HOST_PORT=${POSTGRES_DOCKER_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - FETCHING_SERVER_HOST=fetching
      - FETCHING_SERVER_PORT=8090
    ports:
      - "${BACKEND_SERVER_PORT}:8080"
    depends_on:
      postgres-migrate:
        condition: service_completed_successfully

  fetching:
    build:
      context: ./fetching
      dockerfile: Dockerfile
    environment:
      - REPO_ROOT=/app
      - FETCHING_SERVER_HOST=0.0.0.0
      - FETCHING_SERVER_PORT=8090
      - INSTAGRAM_LOGIN=${INSTAGRAM_LOGIN}
      - INSTAGRAM_PASSWORD=${INSTAGRAM_PASSWORD}
      - STEAM_WEB_API_KEY=${STEAM_WEB_API_KEY}
    volumes:
      - ./settings:/app/settings
    ports:
      - "8090:8090"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_API_URL=http://localhost:${BACKEND_SERVER_PORT}
        - VITE_USE_TESTING_DATA=false
    ports:
      - "5174:80"
    depends_on:
      - backend